# Generated by Django 3.0.8 on 2022-03-08 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deardiaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'verbose_name_plural': 'Diary_Entries'},
        ),
    ]
