# Generated by Django 3.0.8 on 2022-03-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deardiaryapp', '0002_auto_20220308_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Entry',
            field=models.TextField(max_length=200),
        ),
    ]
