# Generated by Django 3.0.8 on 2022-03-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deardiaryapp', '0003_auto_20220308_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='Entry',
            field=models.TextField(),
        ),
    ]
